# Generated by Django 6.0.3 on 2026-03-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
