# Generated by Django 6.0.3 on 2026-03-22 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='accepted_by_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='accepted_by_subadmin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subadmin_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted by Employee'), ('accepted_by_leader', 'Accepted by Leader'), ('accepted_by_subadmin', 'Accepted by Sub-Admin'), ('sent_to_manager', 'Sent to Manager'), ('approved', 'Approved (Generic)'), ('rejected', 'Rejected')], default='submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('team_leader', 'Team Leader'), ('admin', 'Sub-Admin'), ('manager', 'Manager'), ('superadmin', 'SuperAdmin')], default='employee', max_length=20),
        ),
    ]
