# Generated by Django 6.0.3 on 2026-03-22 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_dailyreport_accepted_by_leader_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='accepted_by_leader_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_approvals_tmp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='accepted_by_subadmin_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subadmin_approvals_tmp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted & Saved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_description', models.TextField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4)),
                ('work_duration_calc', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(choices=[('employee_level', 'Employee Level (Approved by Leader)'), ('leader_level', 'Leader Level (Approved by Sub-Admin)')], max_length=20)),
                ('status', models.CharField(default='accepted', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_employee_reports', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_leader_reports', to=settings.AUTH_USER_MODEL)),
                ('subadmin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_subadmin_reports', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_team_reports', to='reports.team')),
            ],
        ),
    ]
