# Generated by Django 6.0.3 on 2026-03-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_dailyreport_accepted_by_leader_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalreport',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
