# Generated by Django 6.0.3 on 2026-03-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_finalreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accumulated_ms',
            field=models.BigIntegerField(default=0),
        ),
    ]
