# Generated by Django 6.0.3 on 2026-03-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_user_accumulated_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_timer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
