# Generated by Django 6.0.3 on 2026-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_issuereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Leader Approval'), ('reviewing', 'In Review'), ('accepted', 'Accepted by Leader'), ('rejected', 'Rejected by Leader'), ('resolved', 'Resolved by Admin')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('reviewing', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
