# Generated by Django 4.2.7 on 2026-03-26 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_issuereport_status_alter_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
