# Generated by Django 5.1.7 on 2026-03-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_timer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
